# This file is an example of pipeline configuration for DQM

# Description of the structure of a pipelines is available in the README.md file

pipeline_definition:
  - domain : "completeness"
    dataset : "tests/sample_data/completeness_sample_data.csv"
    columns_names : ["column_1","column_3","column_6","column_9"]

  - domain : "representativeness"
    metrics: ["chi-square","GRTE","shannon-entropy","kolmogorov-smirnov"]
    bins : 10
    distribution : normal
    dataset: "tests/sample_data/SMD_test_ds_sample.csv"
    columns_names : ["column_2","column_4", "column_6"]
    
  - domain : "diversity"
    metrics: ["simpson","gini"]
    dataset: "tests/sample_data/SMD_test_ds_sample.csv"
    columns_names : ["column_2","column_4", "column_6"]

  - domain: "domain_gap"
    metrics:
      - metric_name: wasserstein
        method_config:
            DATA: 
                batch_size: 32
                height: 299
                width: 299
                norm_mean: [0.485,0.456,0.406]
                norm_std: [0.229,0.224,0.225]
                source: "tests/sample_data/image_test_ds/c20"
                target: "tests/sample_data/image_test_ds/c33"  
            MODEL:
                arch: "resnet18"
                device: "cpu"
                n_layer_feature: -2
            METHOD: 
                name: "wasserstein"
                dimension: "1D"
      - metric_name: FID
        method_config:
                DATA: 
                    batch_size: 32
                    height: 299
                    width: 299
                    norm_mean: [0.485,0.456,0.406]
                    norm_std: [0.229,0.224,0.225]
                    source: "tests/sample_data/image_test_ds/c20"
                    target: "tests/sample_data/image_test_ds/c33"  
                MODEL: 
                    device: "cpu"
                    n_layer_feature: -2
                METHOD: 
                    name: "fid"
      - metric_name: PAD
        method_config:
            DATA: 
                batch_size: 10
                height: 224
                width: 224
                norm_mean: [0.485,0.456,0.406]
                norm_std: [0.229,0.224,0.225]
                source: "tests/sample_data/image_test_ds/c20"
                target: "tests/sample_data/image_test_ds/c33"
            MODEL: 
                arch: ["efficientnet_b0","vgg16"]
                device: "cpu"
                n_layer_feature: -2           
            METHOD: 
                name: "proxy"
                evaluator: "mse"
      - metric_name: KLMVN
        method_config:
                DATA: 
                    batch_size: 10
                    height: 20
                    width: 20
                    norm_mean: [0.485,0.456,0.406]
                    norm_std: [0.229,0.224,0.225]
                    source: "tests/sample_data/image_test_ds/c20"
                    target: "tests/sample_data/image_test_ds/c33"  
                MODEL: 
                    arch: "resnet18"
                    device: "cpu"
                    n_layer_feature: -2

                METHOD: 
                name: "klmvn"
      - metric_name: MMD
        method_config:
                DATA: 
                    batch_size: 10
                    height: 224
                    width: 224
                    norm_mean: [0.485,0.456,0.406]
                    norm_std: [0.229,0.224,0.225]
                    source: "tests/sample_data/image_test_ds/c20"
                    target: "tests/sample_data/image_test_ds/c33"

                MODEL: 
                    arch: "resnet18"
                    device: "cpu"
                    n_layer_feature: -2
                
                METHOD: 
                    name: "mmd"
                    kernel: "linear"
                    kernel_params: 
                        gamma: 1.0
                        degree: 3.0
                        coefficient0: 1.0 
      - metric_name: CMD
        method_config:
                DATA: 
                    batch_size: 10
                    height: 224
                    width: 224
                    norm_mean: [0.485,0.456,0.406]
                    norm_std: [0.229,0.224,0.225]
                    source: "tests/sample_data/image_test_ds/c20"
                    target: "tests/sample_data/image_test_ds/c33" 

                MODEL: 
                    arch: "resnet18"
                    n_layer_feature : ["maxpool","layer1.1.relu_1","layer2.1.relu_1", "layer3.1.relu_1", "layer4.1.relu_1"]
                    feature_extractors_layers_weights : [1, 1, 1, 1, 1]
                    device: "cpu"

                METHOD: 
                    name: "cmd"
                    k: 5